name: Build and Test Package

on:
  push:
    branches: [main]

jobs:
  build:
    name: ğŸ§ª Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ğŸ“¦ Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - name: ğŸ§ª Run Tests
        run: bun run test

  test:
    name: ğŸ—ï¸ Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ğŸ“¦ Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - name: ğŸ—ï¸ Build Package
        run: bun run build
